#!/usr/bin/awk -f

BEGIN {
  floor=0
}
{
  for (i = 1; i <= length($0); i++) {
    instruction=substr($0, i, 1)

    if (instruction == "(") {
      floor++
    } else if (instruction == ")") {
      floor--
    }

    if (floor == -1) {
      print i
      break
    }
  }
}
