#!/usr/bin/awk -f

BEGIN {
  RS=""
  valid=0
}
{
  delete record
  f = 0
  for (i = 1; i <= NF; i++) record[substr($i, 1, 3)] = substr($i, 5) 

  if (record["byr"] >= 1920 && record["byr"] <= 2002) f++
  if (record["iyr"] >= 2010 && record["iyr"] <= 2020) f++
  if (record["eyr"] >= 2020 && record["eyr"] <= 2030) f++

  hgt = record["hgt"]
  h = substr(hgt, 1, length(hgt) - 2)
  u = substr(hgt, length(hgt) - 1)

  if (u == "cm" && h >= 150 && h <= 193) f++
  if (u == "in" && h >= 59 && h <= 79) f++
  if (match(record["hcl"], /^#[0-9a-fA-F]{6}$/)) f++
  if (match(record["ecl"], /^amb|blu|brn|gry|grn|hzl|oth$/)) f++
  if (match(record["pid"], /^[0-9]{9}$/)) f++

  if (f == 7) valid++
}
END {
  print valid
}
